import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  backendSidebar: [
    'backend/intro',
    {
      type: 'category',
      label: 'Admin Apis',
      items: [
        {
          type: 'category',
          label: 'Airtable',
          items: [
            {
              type: 'doc',
              id: 'backend/admin/airtable/get-boats',
              label: 'GET Boats',
            },
            {
              type: 'doc',
              id: 'backend/admin/airtable/import-boats',
              label: 'Import Boats',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bookings',
          items: [
            {
              type: 'doc',
              id: 'backend/admin/bookings/bookings',
              label: 'List Bookings',
            },
            {
              type: 'doc',
              id: 'backend/admin/bookings/booking',
              label: 'Get Booking',
            },
            // {
            //   type: 'doc',
            //   id: 'backend/admin/bookings/booking',
            //   label: 'Edit Booking',
            // },
          ],
        },

        // {
        //   type: 'doc',
        //   id: 'backend/admin/intro',
        //   label: 'Introduction',
        // },
      ],
    },
    // { type: 'category', label: 'Models', items: ['backend/intro'] },
  ],
  // adminSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // clientSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
