import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: ['intro', 'architecture'],
  backendSidebar: [
    'admin/intro',
    {
      type: 'category',
      label: 'Boats Airtable',
      items: [
        {
          type: 'doc',
          id: 'admin/airtable/get-boats',
          label: 'GET Boats',
        },
        {
          type: 'doc',
          id: 'admin/airtable/import-boats',
          label: 'Import Boat',
        },
        {
          type: 'doc',
          id: 'admin/airtable/sync-boat',
          label: 'Sync Boat',
        },
      ],
    },
    {
      type: 'category',
      label: 'Bookings',
      items: [
        {
          type: 'doc',
          id: 'admin/bookings/bookings',
          label: 'List Bookings',
        },
        {
          type: 'doc',
          id: 'admin/bookings/booking',
          label: 'Get Booking',
        },
        {
          type: 'doc',
          id: 'admin/bookings/status-booking',
          label: 'Change Status Booking',
        },
      ],
    },
    {
      type: 'category',
      label: 'Orders',
      items: [
        {
          type: 'doc',
          id: 'admin/orders/list-orders',
          label: 'List Orders',
        },
        {
          type: 'doc',
          id: 'admin/orders/get-order',
          label: 'Get Order',
        },
      ],
    },
    {
      type: 'category',
      label: 'Services',
      items: [
        {
          type: 'doc',
          id: 'admin/services/list-services',
          label: 'List Services',
        },
        {
          type: 'doc',
          id: 'admin/services/get-service',
          label: 'Get Service',
        },
        {
          type: 'doc',
          id: 'admin/services/new-service',
          label: 'New Service',
        },
        {
          type: 'doc',
          id: 'admin/services/edit-service',
          label: 'Edit Service',
        },
      ],
    },
    {
      type: 'category',
      label: 'Products',
      items: [
        {
          type: 'doc',
          id: 'admin/products/list-products',
          label: 'List Products',
        },
        {
          type: 'doc',
          id: 'admin/products/get-product',
          label: 'Get Product',
        },
        {
          type: 'doc',
          id: 'admin/products/new-product',
          label: 'New Product',
        },
        {
          type: 'doc',
          id: 'admin/products/edit-product',
          label: 'Edit Product',
        },
      ],
    },
    // { type: 'category', label: 'Models', items: ['intro'] },
  ],
  // adminSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // clientSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
